//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class receipt
    {
        public int id { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> number_receipt { get; set; }
        public string name { get; set; }
        public string wraiter { get; set; }
        public Nullable<int> table_number { get; set; }
        public Nullable<int> wraiter_id { get; set; }
        public Nullable<int> dishes_id { get; set; }
        public string dishes { get; set; }
        public Nullable<int> table_id { get; set; }
        public Nullable<int> col_dish { get; set; }
        public string email_client { get; set; }
        public Nullable<int> client_id { get; set; }
    
        public virtual Dishes Dishes1 { get; set; }
        public virtual Tables Tables { get; set; }
        public virtual Wraiters Wraiters { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
