//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tables()
        {
            this.receipt = new HashSet<receipt>();
        }
    
        public int id { get; set; }
        public string addres { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> wraiter_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> receipt_id { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receipt> receipt { get; set; }
        public virtual Wraiters Wraiters { get; set; }
    }
}
